image: node:12

stages:
  - build
  - test
  - deploy
  - test deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/


build website:
  stage: build
  script:
    - echo ${CI_COMMIT_SHORT_SHA}
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA" ./public/index.html
  artifacts:
    paths:
      - ./public


test artifacts:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html


test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac| tac | grep -q "Gatsby"


deploy to surge:
  stage: deploy
  script: 
    - npm install -g surge
    - surge --project ./public --domain delicate-cicd.surge.sh


test deployment:
  image: alpine
  stage: test deploy
  script:
    - apk add curl
    - curl -s "http://delicate-cicd.surge.sh" | tac | tac | grep -q "New York"
    - curl -s "http://delicate-cicd.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"