image: node:12

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - test production
  - update cache


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull



build website:
  stage: build
  script:
    - echo ${CI_COMMIT_SHORT_SHA}
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public
  except:
    - schedules



test artifacts:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep "Gatsby" ./public/index.html
  except:
    - schedules



test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac| tac | grep -q "Gatsby"
  except:
    - schedules



deploy to staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_URL
  only: master
  cache: {}
  script: 
    - npm install -g surge
    - surge --project ./public --domain $STAGING_URL
  except:
    - schedules




deploy to production:
  stage: deploy production
  environment:
    name: production
    url: http://$PRODUCTION_URL
  only: master
  cache: {}
  script: 
    - npm install -g surge
    - surge --project ./public --domain $PRODUCTION_URL
  except:
    - schedules



test production:
  image: alpine
  stage: test production
  only: master
  cache: {}
  script:
    - apk add curl
    - curl -s "http://delicate-cicd.surge.sh" | tac | tac | grep -q "New York"
  except:
    - schedules



update the cache:
  stage: update cache
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules
