image: node:12

stages:
  - build
  - test
  - deploy

build website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifacts:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac| tac | grep -q "Gatsby"

deply website to surge:
  stage: deploy
  script: 
    - npm install -g surge
    - surge --project ./public --domain delicate-cicd.surge.sh


